-- AlterTable
ALTER TABLE `permissions` MODIFY `name` ENUM('LIST_USER_ALL', 'LIST_USER_UNIT', 'LIST_USER_ORG', 'UPDATE_USER_ADMIN', 'UPDATE_USER_OWNER', 'UPDATE_USER_BARBER', 'MANAGE_OTHER_USER_TRANSACTION', 'LIST_PERMISSIONS_ALL', 'LIST_ROLES_UNIT', 'LIST_SALES_UNIT', 'LIST_APPOINTMENTS_UNIT', 'LIST_SERVICES_UNIT', 'SELL_PRODUCT', 'SELL_SERVICE', 'SELL_APPOINTMENT', 'ACCEPT_APPOINTMENT', 'CREATE_SALE', 'CREATE_USER_OWNER', 'CREATE_USER_MANAGER', 'CREATE_USER_ATTENDANT', 'CREATE_USER_BARBER', 'CREATE_USER_CLIENT', 'CREATE_USER_ADMIN', 'MANAGE_USER_TRANSACTION_ADD', 'MANAGE_USER_TRANSACTION_WITHDRAWAL', 'LIST_UNIT_ALL', 'LIST_UNIT_ORG', 'LIST_ROLES_ALL', 'MANAGE_SELF_BLOCKED_HOURS', 'MANAGE_SELF_WORK_HOURS', 'MENAGE_USERS_WORKING_HOURS') NOT NULL;

-- AddForeignKey
ALTER TABLE `unit_opening_hours` ADD CONSTRAINT `unit_opening_hours_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `units`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `profile_work_hours` ADD CONSTRAINT `profile_work_hours_profileId_fkey` FOREIGN KEY (`profileId`) REFERENCES `profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
