-- AlterTable
ALTER TABLE `appointments` ADD COLUMN `status` ENUM('SCHEDULED', 'CONFIRMED', 'CANCELED', 'IN_ATTENDANCE', 'CONCLUDED', 'NO_SHOW') NOT NULL DEFAULT 'SCHEDULED', ADD COLUMN `durationService` INTEGER NULL;
