-- AlterTable
ALTER TABLE `permissions` MODIFY `name` ENUM('LIST_USER_ALL', 'LIST_USER_UNIT', 'LIST_USER_ORG', 'UPDATE_USER_ADMIN', 'UPDATE_USER_OWNER', 'UPDATE_USER_BARBER', 'MANAGE_OTHER_USER_TRANSACTION', 'LIST_PERMISSIONS_ALL', 'LIST_ROLES_UNIT', 'LIST_SALES_UNIT', 'LIST_APPOINTMENTS_UNIT', 'LIST_SERVICES_UNIT', 'SELL_PRODUCT', 'MANAGE_USER_TRANSACTION_ADD', 'MANAGE_USER_TRANSACTION_WITHDRAWAL', 'LIST_UNIT_ALL', 'LIST_UNIT_ORG', 'LIST_ROLES_ALL') NOT NULL;

-- CreateTable
CREATE TABLE `barber_products` (
    `id` VARCHAR(191) NOT NULL,
    `profileId` VARCHAR(191) NOT NULL,
    `productId` VARCHAR(191) NOT NULL,
    `commissionPercentage` DOUBLE NULL,
    `commissionType` ENUM('PERCENTAGE_OF_SERVICE', 'PERCENTAGE_OF_USER', 'PERCENTAGE_OF_USER_SERVICE') NOT NULL DEFAULT 'PERCENTAGE_OF_SERVICE',

    UNIQUE INDEX `barber_products_profileId_productId_key`(`profileId`, `productId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `barber_products` ADD CONSTRAINT `barber_products_profileId_fkey` FOREIGN KEY (`profileId`) REFERENCES `profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `barber_products` ADD CONSTRAINT `barber_products_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
